//package testexceljava;

/*---------------------------------------------------------------------------
 | Tutorial 37                                                  
 |                                                                
 | This tutorial shows how to read an Excel XLS file in Java (the
 | XLS file generated by Tutorial 28 as base template), modify
 | some data and save it to another XLS file (Tutorial37 - read XLS file.xls). 
 ---------------------------------------------------------------------------*/

import java.io.FileInputStream;
import EasyXLS.*;

public class Tutorial37 {

  public static void main(String[] args) {
    try {
      System.out.println("Tutorial 37");
      System.out.println("----------");

      // Create an instance of the class that reads Excel files
      ExcelDocument workbook = new ExcelDocument();

      // Read XLS file
      System.out.println("Reading file C:\\Samples\\Tutorial28.xls.");
      FileInputStream file = new FileInputStream("C:\\Samples\\Tutorial28.xls");
      if (workbook.easy_LoadXLSFile(file))
      {
        // Get the table of data for the second worksheet
        ExcelTable xlsSecondTable = ((ExcelWorksheet)workbook.easy_getSheet("Second tab")).easy_getExcelTable();

        // Write some data to the second sheet
        xlsSecondTable.easy_getCell("A1").setValue("Data added by Tutorial37");

        for (int column=0; column<5; column++)
        {
          xlsSecondTable.easy_getCell(1, column).setValue("Data " + (column + 1));
        }

        // Export the new XLS file
        System.out.println("Writing file C:\\Samples\\Tutorial37 - read XLS file.xls.");
        workbook.easy_WriteXLSFile("C:\\Samples\\Tutorial37 - read XLS file.xls");

        // Confirm export of Excel file
        if (workbook.easy_getError().equals(""))
          System.out.println("File successfully created.");
        else
          System.out.println("Error encountered: " + workbook.easy_getError());

      }
	  
	  // Dispose memory
      workbook.Dispose();
    }
    catch (Exception ex) {
      ex.printStackTrace();
    }
  }
}
