//package testexceljava;

/*-------------------------------------------------------------------------------
 | Tutorial 38
 | 
 | This tutorial shows how to read an Excel XLSB file in Java (the
 | XLSB file generated by Tutorial 29 as base template), modify
 | some data and save it to another XLSB file (Tutorial38 - read XLSB file..xlsb).
 -------------------------------------------------------------------------------*/

import java.io.FileInputStream;
import EasyXLS.*;

public class Tutorial38 {

  public static void main(String[] args) {
    try {
      System.out.println("Tutorial 38");
      System.out.println("----------");

      // Create an instance of the class that reads Excel files
      ExcelDocument workbook = new ExcelDocument();

      // Read XLSB file
      System.out.println("Reading file C:\\Samples\\Tutorial29.xlsb.");
      FileInputStream file = new FileInputStream("C:\\Samples\\Tutorial29.xlsb");
      if (workbook.easy_LoadXLSBFile(file))
      {
		// Get the table of data for the second worksheet
        ExcelTable xlsSecondTable = ((ExcelWorksheet)workbook.easy_getSheetAt(1)).easy_getExcelTable();
		
		// Write some data to the second sheet
        xlsSecondTable .easy_getCell("A1").setValue("Data added by Tutorial38");

        for (int column=0; column<5; column++)
        {
          xlsSecondTable .easy_getCell(1, column).setValue("Data " + (column + 1));
        }

        // Export the new XLSB file
        System.out.println("Writing file C:\\Samples\\Tutorial38 - read XLSB file..xlsb.");
        workbook.easy_WriteXLSBFile("C:\\Samples\\Tutorial38 - read XLSB file..xlsb");

        // Confirm export of Excel file
        if (workbook.easy_getError().equals(""))
          System.out.println("File successfully created.");
        else
          System.out.println("Error encountered: " + workbook.easy_getError());

      }
	  
	  // Dispose memory
      workbook.Dispose();
    }
    catch (Exception ex) {
      ex.printStackTrace();
    }
  }
}
