/* ------------------------------------------------------------------------------
 * Tutorial 36
 * 
 * This tutorial shows how to read an Excel XLSX file in C# (the
 * XLSX file generated by Tutorial 04 as base template), modify
 * some data and save it to another XLSX file (Tutorial36 - read XLSX file.xlsx).
 * --------------------------------------------------------------------------- */

using System;
using System.IO;
using System.Data;
using EasyXLS;

public class Tutorial36
{

	[STAThread]
	static void Main() 
	{
		Console.WriteLine("Tutorial 36\n-----------\n");

        // Create an instance of the class that reads Excel files
		ExcelDocument workbook = new ExcelDocument();

        // Read XLSX file
		Console.WriteLine("Reading file C:\\Samples\\Tutorial04.xlsx");
		
		if (workbook.easy_LoadXLSXFile("C:\\Samples\\Tutorial04.xlsx"))
		{
            // Get the table of data for the second worksheet
			ExcelTable xlsSecondTable = ((ExcelWorksheet)workbook.easy_getSheet("Second tab")).easy_getExcelTable();

            // Write some data to the second sheet
			xlsSecondTable.easy_getCell("A1").setValue("Data added by Tutorial36");
			
			for (int column=0; column<5; column++)
			{
				xlsSecondTable.easy_getCell(1, column).setValue("Data " + (column + 1)); 
			}

            // Export the new XLSX file
            Console.WriteLine("\nWriting file C:\\Samples\\Tutorial36 - read XLSX file.xlsx.");
            workbook.easy_WriteXLSXFile("C:\\Samples\\Tutorial36 - read XLSX file.xlsx");

            // Confirm export of Excel file
			String sError = workbook.easy_getError();
			if (sError.Equals(""))
				Console.Write("\nFile successfully created.");
			else
				Console.Write("\nError encountered: " + sError);
		}
		else
		{
			Console.WriteLine("\nError reading file C:\\Samples\\Tutorial04.xlsx \n" + workbook.easy_getError());	
		}

		Console.WriteLine("\nPress Enter to exit ...");
		
		// Dispose memory
		workbook.Dispose();

		Console.ReadLine();
	}
}
