/* ------------------------------------------------------------------------
 * Tutorial 40
 * 
 * This tutorial shows how to convert HTML file to Excel in C#. The
 * HTML file generated by Tutorial 31 is imported, some data is modified
 * and after that is exported as Excel file.
 * --------------------------------------------------------------------- */

using System;
using System.IO;
using System.Data;
using EasyXLS;

public class Tutorial40
{
	
	[STAThread]
	static void Main() 
	{
		Console.WriteLine("Tutorial 40\n-----------\n");

        // Create an instance of the class used to import/export Excel files
		ExcelDocument workbook = new ExcelDocument();

        // Import HTML file
		Console.WriteLine("Reading file C:\\Samples\\Tutorial31.html");
		
		if (workbook.easy_LoadHTMLFile("C:\\Samples\\Tutorial31.html"))
		{
            // Set worksheet name
			workbook.easy_getSheetAt(0).setSheetName("First tab");

            // Add new worksheet and add some data in cells (optional step)
			workbook.easy_addWorksheet("Second tab");
			ExcelTable xlsTable = ((ExcelWorksheet)workbook.easy_getSheetAt(1)).easy_getExcelTable();
			xlsTable.easy_getCell("A1").setValue("Data added by Tutorial40");
						
			for (int column=0; column<5; column++)
			{
				xlsTable.easy_getCell(1, column).setValue("Data " + (column + 1)); 
			}

            // Export Excel file
            Console.WriteLine("\nWriting file C:\\Samples\\Tutorial40 - convert HTML to Excel.xlsx.");
            workbook.easy_WriteXLSXFile("C:\\Samples\\Tutorial40 - convert HTML to Excel.xlsx");

            // Confirm conversion of HTML to Excel
			String sError = workbook.easy_getError();
			if (sError.Equals(""))
				Console.Write("\nFile successfully created.");
			else
				Console.Write("\nError encountered: " + sError);
		}
		else
		{
			Console.WriteLine("\nError reading file C:\\Samples\\Tutorial31.html \n" + workbook.easy_getError());	
		}

		Console.WriteLine("\nPress Enter to exit ...");
		
		// Dispose memory
		workbook.Dispose();

		Console.ReadLine();
	}
}
