/* -----------------------------------------------------------------------------
 * Tutorial 41
 * 
 * This tutorial shows how to convert XML spreadsheet to Excel in C#. The
 * XML Spreadsheet generated by Tutorial 32 is imported, some data is modified
 * and after that is exported as Excel file.
 * -------------------------------------------------------------------------- */

using System;
using System.IO;
using System.Data;
using EasyXLS;

public class Tutorial41
{
	
	[STAThread]
	static void Main() 
	{
		Console.WriteLine("Tutorial 41\n-----------\n");

        // Create an instance of the class used to import/export Excel files
		ExcelDocument workbook = new ExcelDocument();

        // Import XML Spreadsheet file
		Console.WriteLine("Reading file C:\\Samples\\Tutorial32.xml");
		
		if (workbook.easy_LoadXMLSpreadsheetFile("C:\\Samples\\Tutorial32.xml"))
		{
            // Get the table of data from the second sheet and add some data in cells (optional step)
			ExcelTable xlsSecondTable = ((ExcelWorksheet)workbook.easy_getSheet("Second tab")).easy_getExcelTable();
			xlsSecondTable.easy_getCell("A1").setValue("Data added by Tutorial41");
						
			for (int column=0; column<5; column++)
			{
				xlsSecondTable.easy_getCell(1, column).setValue("Data " + (column + 1)); 
			}

            // Export Excel file
            Console.WriteLine("\nWriting file C:\\Samples\\Tutorial41 - convert XML spreadsheet to Excel.xlsx.");
            workbook.easy_WriteXLSXFile("C:\\Samples\\Tutorial41 - convert XML spreadsheet to Excel.xlsx");

            // Confirm conversion of XML Spreadsheet to Excel
			String sError = workbook.easy_getError();
			if (sError.Equals(""))
				Console.Write("\nFile successfully created.");
			else
				Console.Write("\nError encountered: " + sError);
		}
		else
		{
			Console.WriteLine("\nError reading file C:\\Samples\\Tutorial32.xml \n" + workbook.easy_getError());	
		}

		Console.WriteLine("\nPress Enter to exit ...");
		
		// Dispose memory
		workbook.Dispose();

		Console.ReadLine();
	}
}
