/* ------------------------------------------------------------------------------
 * Tutorial 38
 * 
 * This tutorial shows how to read an Excel XLSB file in C# (the
 * XLSB file generated by Tutorial 29 as base template), modify
 * some data and save it to another XLSB file (Tutorial38 - read XLSB file.xlsb).
 * --------------------------------------------------------------------------- */

using System;
using System.IO;
using System.Data;
using EasyXLS;

public class Tutorial38
{

	[STAThread]
	static void Main() 
	{
		Console.WriteLine("Tutorial 38\n-----------\n");

        // Create an instance of the class that reads Excel files
		ExcelDocument workbook = new ExcelDocument();

        // Read XLSB file
		Console.WriteLine("Reading file C:\\Samples\\Tutorial29.xlsb");
		
		if (workbook.easy_LoadXLSBFile("C:\\Samples\\Tutorial29.xlsb"))
		{
            // Get the table of data for the second worksheet
			ExcelTable xlsSecondTable = ((ExcelWorksheet)workbook.easy_getSheet("Second tab")).easy_getExcelTable();

            // Write some data to the second sheet
			xlsSecondTable.easy_getCell("A1").setValue("Data added by Tutorial38");
			
			for (int column=0; column<5; column++)
			{
				xlsSecondTable.easy_getCell(1, column).setValue("Data " + (column + 1)); 
			}

            // Export the new XLSB file
            Console.WriteLine("\nWriting file C:\\Samples\\Tutorial38 - read XLSB file.xlsb.");
            workbook.easy_WriteXLSBFile("C:\\Samples\\Tutorial38 - read XLSB file.xlsb");

            // Confirm export of Excel file
			String sError = workbook.easy_getError();
			if (sError.Equals(""))
				Console.Write("\nFile successfully created.");
			else
				Console.Write("\nError encountered: " + sError);
		}
		else
		{
			Console.WriteLine("\nError reading file C:\\Samples\\Tutorial29.xlsb \n" + workbook.easy_getError());	
		}

		Console.WriteLine("\nPress Enter to exit ...");
		
		// Dispose memory
		workbook.Dispose();

		Console.ReadLine();
	}
}
