/* ----------------------------------------------------------------------
 * Tutorial 39
 * 
 * This tutorial shows how to convert CSV file to Excel in C++. The
 * CSV file generated by Tutorial 30 is imported, some data is modified
 * and after that is exported as Excel file.
 * ------------------------------------------------------------------- */

#include "EasyXLS.h"
#include <conio.h>


int main()
{
	printf("Tutorial 39\n----------\n");

	HRESULT hr;

	// Initialize COM
	hr = CoInitialize(0);

	// Use the SUCCEEDED macro and get a pointer to the interface
	if(SUCCEEDED(hr))
	{
		// Create a pointer to the interface used to import/export Excel files
		EasyXLS::IExcelDocumentPtr workbook;
		hr = CoCreateInstance(__uuidof(EasyXLS::ExcelDocument),
		NULL,
		CLSCTX_ALL,
		__uuidof(EasyXLS::IExcelDocument),
		(void**) &workbook) ;

		if(SUCCEEDED(hr)){

			// Import CSV file	
			printf("\nReading file: C:\\Samples\\Tutorial30.csv\n");
			if (workbook->easy_LoadCSVFile("C:\\Samples\\Tutorial30.csv"))
			{
				// Set worksheet name
				workbook->easy_getSheetAt(0)->setSheetName("First tab");

				// Add new worksheet and add some data in cells (optional step)
				workbook->easy_addWorksheet_2("Second tab"); 
				EasyXLS::IExcelWorksheetPtr xlsSecondTab = (EasyXLS::IExcelWorksheetPtr)workbook->easy_getSheetAt(1);
				EasyXLS::IExcelTablePtr xlsTable = xlsSecondTab->easy_getExcelTable();
				xlsTable->easy_getCell_2("A1")->setValue("Data added by Tutorial39");

				char* cellValue = (char*)malloc(11*sizeof(char));
				char*  columnNumber = (char*)malloc(sizeof(char));
				for (int column=0; column<5; column++)
				{
					strcpy_s(cellValue, 6, "Data ");			
					_itoa_s(column+ 1, columnNumber, 2, 10);
					strcat_s(cellValue, 10, columnNumber);
					xlsTable->easy_getCell(1, column)->setValue(cellValue);
				}
			
				
				// Export Excel file
				printf("Writing file C:\\Samples\\Tutorial39 - convert CSV to Excel.xlsx.");
				workbook->easy_WriteXLSXFile("C:\\Samples\\Tutorial39 - convert CSV to Excel.xlsx");
				
				// Confirm conversion of CSV to Excel
				_bstr_t sError = workbook->easy_getError();
				if (strcmp(sError, "") == 0){
					printf("\nFile successfully created. Press Enter to Exit...");
				}
				else{
					printf("\nError encountered: %s", (LPCSTR)sError); 
				}
			}
			else
			{
				printf("\nError reading file C:\\Samples\\Tutorial30.csv %s\n", (LPCSTR)((_bstr_t)workbook->easy_getError())); 
			}

			// Dispose memory
			workbook->Dispose();
		}
		else{
			printf("Object is not available!");
		}
	}
	else{
		printf("COM can't be initialized!");
	}

	// Uninitialize COM
	CoUninitialize();

	_getch();
	return 0;
}
