Attribute VB_Name = "Format"
Public FORMAT_FORMAT_GENERAL As String
Public FORMAT_FORMAT_INTEGER As String
Public FORMAT_FORMAT_FLOAT_2DECIMALS As String
Public FORMAT_FORMAT_INTEGER_PERCENT As String
Public FORMAT_FORMAT_FLOAT_2DECIMALS_PERCENT As String
Public FORMAT_FORMAT_DATE_REGIONAL_SETTINGS As String
Public FORMAT_FORMAT_DATE_WEEKDAY_REGIONAL_SETTINGS As String
Public FORMAT_FORMAT_DATE_AND_TIME_REGIONAL_SETTINGS As String
Public FORMAT_FORMAT_DATE_TIME_REGIONAL_SETTINGS As String
Public FORMAT_FORMAT_DATE As String
Public FORMAT_FORMAT_DATE_TIME As String
Public FORMAT_FORMAT_CURRENCY As String
Public FORMAT_FORMAT_AS_HALVES As String
Public FORMAT_FORMAT_AS_QUARTERS As String
Public FORMAT_FORMAT_AS_TENTHS As String

Sub Initialize()
        FORMAT_FORMAT_GENERAL = "General"
        FORMAT_FORMAT_INTEGER = "0"
        FORMAT_FORMAT_FLOAT_2DECIMALS = "0.00"
        FORMAT_FORMAT_INTEGER_PERCENT = "0%"
        FORMAT_FORMAT_FLOAT_2DECIMALS_PERCENT = "0.00%"
        FORMAT_FORMAT_DATE_REGIONAL_SETTINGS = "Short Date"
        FORMAT_FORMAT_DATE_WEEKDAY_REGIONAL_SETTINGS = "[$-F800]dddd\\,\\ mmmm\\ dd\\,\\ yyyy"
        FORMAT_FORMAT_DATE_AND_TIME_REGIONAL_SETTINGS = "General Date"
        FORMAT_FORMAT_DATE_TIME_REGIONAL_SETTINGS = "[$-F400]h:mm:ss\\ AM/PM"
        FORMAT_FORMAT_DATE = "MM/dd/yyyy"
        FORMAT_FORMAT_DATE_TIME = "MM/dd/yyyy HH:mm:ss"
        FORMAT_FORMAT_CURRENCY = "$0.00"
        FORMAT_FORMAT_AS_HALVES = "# ?/2"
        FORMAT_FORMAT_AS_QUARTERS = "# ?/4"
        FORMAT_FORMAT_AS_TENTHS = "# ?/10"
End Sub
