"""-----------------------------------------------------------------
Tutorial 39

This tutorial shows how to convert CSV file to Excel in Python. The
CSV file generated by Tutorial 30 is imported, some data is modified
and after that is exported as Excel file.
-----------------------------------------------------------------"""

import gc

from py4j.java_gateway import JavaGateway
from py4j.java_gateway import java_import 
gateway = JavaGateway()

java_import(gateway.jvm,'EasyXLS.*')

print("Tutorial 39\n-----------\n")

# Create an instance of the class used to import/export Excel files
workbook = gateway.jvm.ExcelDocument()

# Import CSV file
print("Reading file C:\\Samples\\Tutorial30.csv")
		
if workbook.easy_LoadCSVFile("C:\\Samples\\Tutorial30.csv"):
    # Set worksheet name
	workbook.easy_getSheetAt(0).setSheetName("First tab")

    # Add new worksheet and add some data in cells (optional step)
	workbook.easy_addWorksheet("Second tab")
	xlsTable = workbook.easy_getSheetAt(1).easy_getExcelTable()
	xlsTable.easy_getCell("A1").setValue("Data added by Tutorial39")
						
	for column in range(5):
		xlsTable.easy_getCell(1, column).setValue("Data " + str(column + 1))

    # Export Excel file
	print("\nWriting file C:\\Samples\\Tutorial39 - convert CSV to Excel.xlsx.")
	workbook.easy_WriteXLSXFile("C:\\Samples\\Tutorial39 - convert CSV to Excel.xlsx")

    # Confirm conversion of CSV to Excel
	sError = workbook.easy_getError()

	if sError == "":
		print("\nFile successfully created.\n")
	else:
            print("\nError encountered: " + sError + "\n")
else:
	print("\nError reading file C:\\Samples\\Tutorial30.csv \n" + workbook.easy_getError())
		
# Dispose memory
gc.collect()