"""------------------------------------------------------------------
Tutorial 40

This tutorial shows how to convert HTML file to Excel in Python. The
HTML file generated by Tutorial 31 is imported, some data is modified
and after that is exported as Excel file.
------------------------------------------------------------------"""

import gc

from py4j.java_gateway import JavaGateway
from py4j.java_gateway import java_import 
gateway = JavaGateway()

java_import(gateway.jvm,'EasyXLS.*')

print("Tutorial 40\n-----------\n")

# Create an instance of the class used to import/export Excel files
workbook = gateway.jvm.ExcelDocument()

# Import HTML file
print("Reading file C:\\Samples\\Tutorial31.html")
		
if workbook.easy_LoadHTMLFile("C:\\Samples\\Tutorial31.html"):
    # Set worksheet name
	workbook.easy_getSheetAt(0).setSheetName("First tab")

    # Add new worksheet and add some data in cells (optional step)
	workbook.easy_addWorksheet("Second tab")
	xlsTable = workbook.easy_getSheetAt(1).easy_getExcelTable()
	xlsTable.easy_getCell("A1").setValue("Data added by Tutorial40")
						
	for column in range(5):
		xlsTable.easy_getCell(1, column).setValue("Data " + str(column + 1))

    # Export Excel file
	print("\nWriting file C:\\Samples\\Tutorial40 - convert HTML to Excel.xlsx.")
	workbook.easy_WriteXLSXFile("C:\\Samples\\Tutorial40 - convert HTML to Excel.xlsx")

    # Confirm conversion of HTML to Excel
	sError = workbook.easy_getError()

	if sError == "":
		print("\nFile successfully created.\n")
	else:
            print("\nError encountered: " + sError + "\n")
else:
	print("\nError reading file C:\\Samples\\Tutorial31.html \n" + workbook.easy_getError())
		
# Dispose memory
gc.collect()