<%@ Language=VBScript %>

<%
	'===============================================================================
	' Tutorial 38
	'
	' This tutorial shows how to read an Excel XLSB file in Classic ASP
	' (the XLSB file generated by Tutorial 29 as base template), modify
	' some data and save it to another XLSB file (Tutorial38 - read XLSB file.xlsb).
	'===============================================================================
	
	response.write("Tutorial 38<br>")
	response.write("----------<br>")

	' Create an instance of the class that reads Excel files
	set workbook = Server.CreateObject("EasyXLS.ExcelDocument")
	
	' Read XLSB file
	response.write("Reading file: C:\Samples\Tutorial29.xlsb<br>")
	if (workbook.easy_LoadXLSBFile("C:\Samples\Tutorial29.xlsb")) then

		' Get the table of data for the second worksheet
		set xlsTable = workbook.easy_getSheet("Second tab").easy_getExcelTable()
		
		' Write some data to the second sheet
		xlsTable.easy_getCell_2("A1").setValue("Data added by Tutorial38")

		for column=0 to 4
			xlsTable.easy_getCell(1, column).setValue("Data " & (column + 1))
		next
		
		' Export the new XLSB file
		response.write("Writing file: C:\Samples\Tutorial38 - read XLSB file.xlsb<br>")
		workbook.easy_WriteXLSBFile ("C:\Samples\Tutorial38 - read XLSB file.xlsb")
		
		' Confirm export of Excel file
		if workbook.easy_getError() = "" then
			response.write("File successfully created.")
		else
			response.write("Error encountered: " + workbook.easy_getError())
		end if
	else
		response.write("Error reading file C:\Samples\Tutorial29.xlsb")
		response.write(workbook.easy_getError())
	end if
	
	' Dispose memory
	workbook.Dispose
%>
