'------------------------------------------------------------------------------
' Tutorial 36
'
' This tutorial shows how to read an Excel XLSX file in VB.NET (the
' XLSX file generated by Tutorial 04 as base template), modify
' some data and save it to another XLSX file (Tutorial36 - read XLSX file.xlsx).
'------------------------------------------------------------------------------

Imports EasyXLS
Imports System.IO

Module Tutorial36

    Sub Main()


        Console.WriteLine("Tutorial 36" & vbCrLf & "----------" & vbCrLf)

        ' Create an instance of the class that reads Excel files
        Dim workbook As New ExcelDocument

        ' Read XLSX file
        Console.WriteLine("Reading file C:\Samples\Tutorial04.xlsx." & vbCrLf)
        If (workbook.easy_LoadXLSXFile("C:\Samples\Tutorial04.xlsx")) Then

            ' Get the table of data for the second worksheet
            Dim xlsSecondTab As ExcelWorksheet = workbook.easy_getSheet("Second tab")
            Dim xlsSecondTable = xlsSecondTab.easy_getExcelTable

            ' Write some data to the second sheet
            xlsSecondTable.easy_getCell("A1").setValue("Data added by Tutorial36")

            For column As Integer = 0 To 4
                xlsSecondTable.easy_getCell(1, column).setValue("Data " & (column + 1))
            Next

            ' Export the new XLSX file
            Console.WriteLine(vbCrLf & "Writing file C:\Samples\Tutorial36 - read XLSX file.xlsx.")
            workbook.easy_WriteXLSXFile("C:\Samples\Tutorial36 - read XLSX file.xlsx")

            ' Confirm export of Excel file
            Dim sError As String = workbook.easy_getError()
            If (sError.Equals("")) Then
                Console.Write(vbCrLf & "File successfully created.")
            Else
                Console.Write(vbCrLf & "Error encountered: " & sError)
            End If
        Else
            Console.WriteLine(vbCrLf & "Error reading file C:\Samples\Tutorial04.xlsx " & vbCrLf & workbook.easy_getError())
        End If

        ' Dispose memory
        workbook.Dispose()

        Console.WriteLine(vbCrLf & "Press Enter to Exit...")
        Console.ReadLine()
    End Sub

End Module
