<%@ Language=VBScript %>

<%
	'============================================================================
	' Tutorial 37
	'
	' This tutorial shows how to read an Excel XLS file in ASP classic
	' (the XLS file generated by Tutorial 28 as base template), modify
	' some data and save it to another XLS file (Tutorial37 - read XLS file.xls).
	'============================================================================
	
	response.write("Tutorial 37<br>")
	response.write("----------<br>")

	' Create an instance of the class that reads Excel files
	set workbook = Server.CreateObject("EasyXLS.ExcelDocument")
	
	' Read XLS file
	response.write("Reading file: C:\Samples\Tutorial28.xls<br>")
	if (workbook.easy_LoadXLSFile("C:\Samples\Tutorial28.xls")) then
		' Get the table of data for the second worksheet
		set xlsSecondTable = workbook.easy_getSheet("Second tab").easy_getExcelTable()
		
		' Write some data to the second sheet
		xlsSecondTable.easy_getCell_2("A1").setValue("Data added by Tutorial37")

		for column=0 to 4
			xlsSecondTable.easy_getCell(1, column).setValue("Data " & (column + 1))
		next
		
		' Export the new XLS file
		response.write("Writing file: C:\Samples\Tutorial37 - read XLS file.xls<br>")
		workbook.easy_WriteXLSFile ("C:\Samples\Tutorial37 - read XLS file.xls")
		
		' Confirm export of Excel file
		if workbook.easy_getError() = "" then
			response.write("File successfully created.")
		else
			response.write("Error encountered: " + workbook.easy_getError())
		end if
	else
		response.write("Error reading file C:\Samples\Tutorial28.xls ")
		response.write(workbook.easy_getError())
	end if
	
	' Dispose memory
	workbook.Dispose
%>
