    '============================================================================
    ' Tutorial 37
    '
    ' This tutorial shows how to read an Excel XLS file in VBScript
	' (the XLS file generated by Tutorial 28 as base template), modify
	' some data and save it to another XLS file (Tutorial37 - read XLS file.xls).
    '============================================================================
    
    WScript.StdOut.WriteLine("Tutorial 37" & vbcrlf & "-----------" & vbcrlf)
  
	' Create an instance of the class that reads Excel files
	Set workbook = CreateObject("EasyXLS.ExcelDocument")
    
    ' Read XLS file
    WScript.StdOut.WriteLine("Reading file: C:\Samples\Tutorial28.xls" & vbcrlf)
    If (workbook.easy_LoadXLSFile("C:\Samples\Tutorial28.xls")) Then
		' Get the table of data for the second worksheet
        Set xlsSecondTable = workbook.easy_getSheet("Second tab").easy_getExcelTable()
        
		' Write some data to the second sheet
		xlsSecondTable.easy_getCell_2("A1").setValue("Data added by Tutorial37")

		For column=0 To 4
			xlsSecondTable.easy_getCell(1, column).setValue("Data " & (column + 1))
		Next
        
        ' Export the new XLS file
        Wscript.StdOut.WriteLine(vbcrlf & "Writing file: C:\Samples\Tutorial37 - read XLS file.xls")
        workbook.easy_WriteXLSFile ("C:\Samples\Tutorial37 - read XLS file.xls")
    
		' Confirm export of Excel file
		Dim sError
		sError = workbook.easy_getError()
		If sError = "" Then
			WScript.StdOut.WriteLine(vbcrlf & "File successfully created.")
		Else
			WScript.StdOut.WriteLine(vbcrlf & "Error: " & sError)
		End If
    
    Else
        Wscript.StdOut.WriteLine("Error reading file C:\Samples\Tutorial28.xls" & vbcrlf & workbook.easy_getError())
    End If
    
	' Dispose memory
	workbook.Dispose
    
    Wscript.StdOut.Write(vbcrlf & "Press Enter to exit ...")
    Wscript.StdIn.ReadLine()
